services:
  postgres:
    ports:
      - "55433:5432"

  redis:
    ports:
      - "56379:6379"

  kafka:
    ports:
      - "59092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://127.0.0.1:59092

  clamav:
    ports:
      - "53310:3310"
